version: '3.7'

services:
  db_mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    container_name: db_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Fayser17"
      MYSQL_DATABASE: "mechanicsdb"
      MYSQL_USER: "userdev"
      MYSQL_PASSWORD: "comuserdev"
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      - db-net

  pikitmechapi:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: pikitmechapi
      restart: always
      ports:
        - 8090:8090
      environment:
        - "PORT=${PORT}"
        - "SALT_CRY=${SALT_CRY}"
        - "NODE_ENV=${NODE_ENV}"
        - "BASIC_PATH=${BASIC_PATH}"
        - "SERVER_KEY=${SERVER_KEY}"
        - "DB_DIALECT=${DB_DIALECT}"
        - "SECRET_KEY=${SECRET_KEY}"
        - "DB_PORT=${DB_PORT}"
        - "DB_NAME_DEV=${DB_NAME_DEV}"
        - "DB_USER_DEV=${DB_USER_DEV}"
        - "DB_PASS_DEV=${DB_PASS_DEV}"
        - "DB_HOST_DEV=${DB_HOST_DEV}"
        - "DB_NAME_TEST=${DB_NAME_TEST}"
        - "DB_USER_TEST=${DB_USER_TEST}"
        - "DB_PASS_TEST=${DB_PASS_TEST}"
        - "DB_HOST_TEST=${DB_HOST_TEST}"
        - "DB_NAME=${DB_NAME}"
        - "DB_USER=${DB_USER}"
        - "DB_PASS=${DB_PASS}"
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      volumes:
        - ./:/opt/app
      stdin_open: true
      tty: true
      depends_on:
        - db_mysql
      links:
        - db_mysql:db_mysql
      networks:
        - db-net

volumes:
  schemas: {}
networks:
    db-net: